### ISSUE TITLE
just the first build error

### ISSUE THREAD

**Issue by ffischer1984** [jeweltheme/basix-admin#2]
ERROR in ./src/components/index.js
Module not found: Error: Can't resolve './icons/Icons.vue' in '/home/fa/projekte/private/iWantThatJob/frontend/basix/src/components'
 @ ./src/components/index.js 17:0-38
 @ ./src/main.js

**Comment by 305088020** [comment]
some files has disappear , such as : "icons/Icons.vue”, "chartjs"

**Comment by litonarefin** [comment]
Build Functionality Added and All Files updated
