### ISSUE TITLE
some files has disappeared

### ISSUE THREAD

**Issue by 305088020** [jeweltheme/basix-admin#3]
some files has disappeared , such as : "icons/Icons.vue”, "chartjs"

**Comment by jeweltheme** [comment]
We'll update Template. Please keep in touch.

**Comment by 4rweb** [comment]
Hello, Has the template been updated?

**Comment by jeweltheme** [comment]
Updated On ThemeForest : https://themeforest.net/item/basix-admin-vuejs-bootstrap-admin-dashboard-template/20838455
We'll be updated on Github by next week, we're working on it.
Thanks

**Comment by jeweltheme** [comment]
Full Template Updated with e new Look
