### ISSUE TITLE
cant build

### ISSUE THREAD

**Issue by torrhet** [jeweltheme/basix-admin#6]
and not working on ie 11

>                                            18.build.js.map      30 kB      18  [emitted]
>                                            19.build.js.map    24.9 kB      19  [emitted]
>                                               build.js.map    1.56 MB      20  [emitted]         main
> 
> WARNING in ./src/views/dashboard/charts/RevenueChart.vue
> 16:2-16 "export 'default' (imported as '__vue_script__') was not found in '!!babel-loader!../../../../node_modules/vue-loader/lib/selector?type=script&index=0!./RevenueChart.vue'
>  @ ./src/views/dashboard/charts/RevenueChart.vue
>  @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/dashboard/Revenue.vue
>  @ ./src/views/dashboard/Revenue.vue
>  @ ./node_modules/babel-loader/lib!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./src/views/Dashboard.vue
>  @ ./src/views/Dashboard.vue
>  @ ./src/router/routes.js
>  @ ./src/main.js
> 
> ERROR in 0.build.js from UglifyJs
> Unexpected token: punc (() [0.build.js:18803,9]
> 
> ERROR in 1.build.js from UglifyJs
> Unexpected token: punc (() [1.build.js:11723,8]
> 
> ERROR in 2.build.js from UglifyJs
> Unexpected token: punc (() [2.build.js:18116,8]
> 
> ERROR in 3.build.js from UglifyJs
> Unexpected token: punc (() [3.build.js:11536,8]
> 
> ERROR in 4.build.js from UglifyJs
> Unexpected token: punc (() [4.build.js:272,9]
> 
> ERROR in 5.build.js from UglifyJs
> Unexpected token: punc (() [5.build.js:239,17]
> 
> ERROR in 6.build.js from UglifyJs
> Unexpected token: punc (() [6.build.js:443,9]
> 
> ERROR in 7.build.js from UglifyJs
> Unexpected token: punc (() [7.build.js:247,6]
> 
> ERROR in 10.build.js from UglifyJs
> Unexpected token: punc (() [10.build.js:120,17]
> 
> ERROR in 11.build.js from UglifyJs
> Unexpected token: punc (() [11.build.js:93,17]
> 
> ERROR in 12.build.js from UglifyJs
> Unexpected token: punc (() [12.build.js:876,9]
> 
> ERROR in build.js from UglifyJs
> Unexpected token: punc (() [build.js:11805,6]
> error Command failed with exit code 2.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by litonarefin** [comment]
Built Functionality Added. You can check now.
